apiVersion: apps/v1
kind: Deployment
metadata:
  name: universal-sql-vmm
  labels:
    app: universal-sql-vmm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: universal-sql-vmm
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: universal-sql-vmm
    spec:
      containers:
      - name: universal-sql-vmm
        image: ${DOCKER_REGISTRY}/universal-sql-vmm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 3443
          name: https
        - containerPort: 50051
          name: grpc
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HTTPS_PORT
          value: "3443"
        - name: USE_HTTPS
          value: "true"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: universal-sql-vmm-secrets
              key: jwt-secret
        - name: JWT_EXPIRATION
          value: "1h"
        - name: QUERY_CACHE_TTL
          value: "60000"
        - name: QUERY_CACHE_MAX_SIZE
          value: "1000"
        - name: DATABASE_TIMEOUT
          value: "5000"
        - name: REDIS_TIMEOUT
          value: "2000"
        - name: KAFKA_TIMEOUT
          value: "10000"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: certs-volume
          mountPath: /app/certs
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: certs-volume
        secret:
          secretName: universal-sql-vmm-certs
      - name: logs-volume
        emptyDir: {}