apiVersion: v1
kind: Secret
metadata:
  name: universal-sql-vmm-secrets
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # Example: echo -n "your-secret" | base64
  jwt-secret: Y2hhbmdlLXRoaXMtaW4tcHJvZHVjdGlvbg==  # change-this-in-production
  encryption-key: MzJjaGFyYWN0ZXJzZWNyZXRrZXlmb3JlbmNyeXB0aW9u  # 32charactersecretkeyforencryption
  encryption-iv: MTZjaGFyc2VjcmV0aXY=  # 16charsecretiv